version: "3"
services:
  postgres:
    image: library/postgres:15
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  gateway_service:
    build: services
    container_name: gateway_service
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - library_system
      - rating_system
      - reservation_system
      - identity_provider
    volumes:
      - ./services/gateway_service:/var/www/html
      - ./services/db_connect:/var/www/html/db_connect
    command: bash -c "composer install && apache2-foreground"

  reservation_system:
    build: services
    container_name: reservation_system
    restart: always
    ports:
      - "8070:80"
    depends_on:
      - postgres
      - identity_provider
    volumes:
      - ./services/reservation_system:/var/www/html
      - ./services/db_connect:/var/www/html/db_connect
    command: bash -c "composer install && php db_connect/load_jwks.php && apache2-foreground"

  library_system:
    build: services
    container_name: library_system
    restart: always
    ports:
      - "8060:80"
    depends_on:
      - postgres
      - identity_provider
    volumes:
      - ./services/library_system:/var/www/html
      - ./services/db_connect:/var/www/html/db_connect
    command: bash -c "composer install && php db_connect/load_jwks.php && apache2-foreground"

  rating_system:
    build: services
    container_name: rating_system
    restart: always
    ports:
      - "8050:80"
    depends_on:
      - postgres
      - identity_provider
    volumes:
      - ./services/rating_system:/var/www/html
      - ./services/db_connect:/var/www/html/db_connect
    command: bash -c "composer install && php db_connect/load_jwks.php && apache2-foreground"

  identity_provider:
    build: services
    container_name: identity_provider
    restart: always
    ports:
      - "8040:80"
    depends_on:
      - postgres
    volumes:
      - ./services/identity_provider:/var/www/html
      - ./services/db_connect:/var/www/html/db_connect
    command: bash -c "composer install && php jwksGenerator.php && apache2-foreground"

volumes:
  db-data: